name: boppos-bluebuild
description: "BoppOS based on Bazzite-dx, optimized for AMD Hardware"
base-image: ghcr.io/ublue-os/bazzite-dx
image-version: stable
# base-image: ghcr.io/ripps818/boppos-bluebuild
# image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: copy
    src: boppos.priv
    dest: /usr/share/boppos/keys/boppos.priv

  - type: script
    scripts:
      - check-files.sh
      - kernel-prebuild.sh

  - type: dnf
    repos:
      cleanup: true
      copr:
        - ilyaz/LACT
        - brycensranch/gpu-screen-recorder-git
        - jackgreiner/lsfg-vk-git
        - codifryed/CoolerControl
        - hikariknight/looking-glass-kvmfr
        - bieszczaders/kernel-cachyos
        - bieszczaders/kernel-cachyos-addons
      files:
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
        - https://repository.mullvad.net/rpm/stable/mullvad.repo
        - https://pkg.cloudflareclient.com/cloudflare-warp-ascii.repo
      nonfree: rpmfusion

    remove:
      auto-remove: true
      packages:
        - hhd
        - hhd-ui
        - kernel
        - kernel-core
        - kernel-modules
        - kernel-modules-core
        - kernel-modules-extra
        - kernel-modules-akmods
        - kernel-devel-matched
        - mesa-va-drivers-freeworld

    install:
      skip-unavailable: true
      allow-erasing: true
      packages:
        # --- EXPLICITLY REQUEST TERRA MESA ---
        # Listing these forces DNF to pick the highest version (Terra)
        # and swap out the Fedora stock ones.
        - mesa-dri-drivers
        - mesa-vulkan-drivers
        - mesa-libgbm
        - mesa-libglapi
        # CachyOS Kernel
        - kernel-cachyos
        - kernel-cachyos-core
        - kernel-cachyos-modules
        - kernel-cachyos-devel-matched
        # CachyOS Addons
        - ananicy-cpp
        - cachyos-ananicy-rules
        - cachyos-ksm-settings
        - cachyos-settings
        - sbsigntools
        - scx-manager
        - scx-scheds
        - scx-tools
        # Gaming
        - antimicrox
        - goverlay
        - inputplumber
        - lsfg-vk
        - lsfg-vk-ui
        # Hardware
        - coolercontrol
        - lact
        - openrgb
        - steam-devices
        # Networking
        - mullvad-vpn
        - cloudflare-warp
        # Virtual Machine
        - virt-manager
        - podman-compose
        - cargo
        # Multimedia
        - ffmpeg
        - gpu-screen-recorder-ui
        - mpv
        - yt-dlp
        # CLI
        - google-noto-fonts-all
        - atuin
        - bat
        - byobu
        - fd-find
        - ripgrep
        - tealdeer
        - ugrep
        - zoxide

  - type: build-kmods
    source: local
    repos:
      copr:
        - hikariknight/looking-glass-kvmfr
      files:
        - terra-source.repo
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
      nonfree: rpmfusion
    kernel:
      package: kernel-cachyos
      devel: kernel-cachyos-devel-matched
    cleanup:
      packages:
        - rpmfusion-free-release
        - rpmfusion-nonfree-release
      files:
        - /etc/yum.repos.d/terra.repo
        - /etc/yum.repos.d/terra-source.repo
        - /etc/yum.repos.d/_copr*hikariknight-looking-glass-kvmfr.repo
    build_deps:
      - python3-setuptools
    modules:
      - name: xone
        source:
          package: akmod-xone
        extras:
          - xone
          - xone-firmware
      - name: xpad-noone
        source:
          package: akmod-xpad-noone
        extras:
          - xpad-noone
      - name: kvmfr
        source:
          package: akmod-kvmfr
        builddir: "LookingGlass-master/module"

  - type: sbsign 
    source: local
    keys:
      priv: /usr/share/boppos/keys/boppos.priv
      pem: /usr/share/boppos/keys/boppos.pem

  - type: justfiles
    validate: true
    install: true
    include:
      - 60-boppos.just

  - type: script
    scripts:
      - fix-just-collision.sh
      - install-joystick-blacklist.sh
      - kernel-postbuild.sh

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        repo:
          title: Flathub (system)
        install:
          - org.mozilla.firefox
          - net.mullvad.MullvadBrowser
          - com.github.tchx84.Flatseal
          - io.github.flattool.Warehouse
          - io.missioncenter.MissionCenter
          - com.heroicgameslauncher.hgl
          - io.github.Faugus.faugus-launcher
          - com.vysp3r.ProtonPlus
        check: false

  - type: systemd
    system:
      enabled:
        - ananicy-cpp.service
        - inputplumber.service
        - ksmd.service
        - lactd.service
        - libvirtd.service
        - openrgb.service
        - scx_loader.service
      disabled:
        - coolercontrold.service
        - mullvad-daemon.service
        - tailscaled.service
        - warp-svc.service

  - type: kargs
    kargs:
      - iommu=pt
      - preempt=full
      - transparent_hugepage=madvise
      - transparent_hugepage.defrag=defer+madvise
      - amdgpu.ppfeaturemask=0xffffffff
      - amdgpu.gpu_recovery=1
      - split_lock_detect=off
      - zswap.enabled=1

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - FiraMono
        - Hack
        - SourceCodePro
        - Terminus
        - Meslo
        - Monoid
        - JetBrainsMono
        - DejaVuSansMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Alegreya
        - Cabin
        - Inter
        - Lato
        - Montserrat
        - Mulish
        - Open Sans
        - Roboto
        - Rubik

  - type: signing
