# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: boppos-bluebuild
description: "BoppOS based on Bazzite-dx, optimized for AMD Hardware"
base-image: ghcr.io/ublue-os/bazzite-dx
image-version: stable

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: script
    scripts:
      - check-files.sh
      - kernel-prebuild.sh

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Alegreya
        - Cabin
        - Inter
        - Lato
        - Montserrat
        - Mulish
        - Open Sans
        - Roboto
        - Rubik

  - type: dnf
    repos:
      cleanup: true
      copr:
        - ilyaz/LACT
        - brycensranch/gpu-screen-recorder-git
        - jackgreiner/lsfg-vk-git
        - codifryed/CoolerControl
        - hikariknight/looking-glass-kvmfr
        - bieszczaders/kernel-cachyos
        - bieszczaders/kernel-cachyos-addons
        - chenxiaolong/sbctl
      files: 
        - helium-browser.repo
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
        - https://repository.mullvad.net/rpm/stable/mullvad.repo
        - https://pkg.cloudflareclient.com/cloudflare-warp-ascii.repo
      nonfree: rpmfusion

    remove:
      auto-remove: true
      packages:
        - hhd
        - hhd-ui
        - kernel
        - kernel-core 
        - kernel-modules 
        - kernel-modules-core 
        - kernel-modules-extra
        - kernel-modules-akmods
        - kernel-devel-matched

    install:
      skip-unavailable: true
      allow-erasing: true
      packages:
        # CachyOS Kernel
        - kernel-cachyos
        - kernel-cachyos-core
        - kernel-cachyos-modules
        - kernel-cachyos-devel-matched
        # CachyOS Addons
        - ananicy-cpp
        - cachyos-ananicy-rules
        - cachyos-ksm-settings
        - cachyos-settings
        - sbsigntools
        - scx-manager
        - scx-scheds
        - scx-tools
        # Gaming
        - antimicrox
        - goverlay
        - inputplumber
        - lsfg-vk
        - lsfg-vk-ui
        # Hardware
        - coolercontrol
        - lact
        - openrgb
        - steam-devices
        # Networking
        - helium-browser
        - mullvad-vpn
        - cloudflare-warp
        # Virtual Machine
        - virt-manager
        - podman-compose
        - cargo
        # Multimedia
        - ffmpeg
        - gpu-screen-recorder-ui
        - gpu-screen-recorder-gtk 
        - mpv
        - yt-dlp
        # CLI
        - atuin
        - bat
        - byobu
        - fd-find
        - ripgrep
        - tealdeer
        - ugrep
        - zoxide

  - type: script
    scripts:
      - build-kmods.sh
      - sign-kmods.sh
      - kernel-postbuild.sh
      - setup-mok-just.sh

  - type: default-flatpaks
    configurations:
      - scope: user
        repo:
          title: Flathub (user)
      - notify: true
        scope: system
        repo:
          title: Flathub (system)
        install:
          - org.mozilla.firefox
          - net.mullvad.MullvadBrowser
          - com.github.tchx84.Flatseal
          - io.github.flattool.Warehouse
          - io.missioncenter.MissionCenter
          - com.heroicgameslauncher.hgl
          - io.github.Faugus.faugus-launcher
          - com.vysp3r.ProtonPlus
          - org.freedesktop.Platform.VulkanLayer.gamescope

  - type: systemd
    system:
      enabled:
        - ananicy-cpp.service
        - inputplumber.service
        - ksmd.service
        - lactd.service
        - libvirtd.service
        - openrgb.service
        - scx_loader.service
      disabled:
        - coolercontrold.service
        - mullvad-daemon.service
        - tailscaled.service
        - warp-svc.service

  - type: kargs
    arch: x86_64
    kargs:
      - amd_iommu=on
      - amdgpu.ppfeaturemask=0xffffffff
      - iommu=pt
      - kvmfr.static_size_mb=128